エラー追加
Replay95/api-cooperation-react pull request #2
Opened 2024-07-18 02:39 UTC by Replay95

指摘どおり新規登録時のエラー報告作成
および新規登録成功時の画面遷移のファイル作成および名称修正完了しました

2024-07-28 08:20 UTC, Replay95 commented
409エラーと500エラーの条件分岐追加しました

2024-07-28 08:22 UTC, Replay95 commented
不要なコードも削除しました

2024-07-28 18:04 UTC, kei95 requested changes
使用されてないパッケージが含まれてるのと、エラーのハンドリングが怪しいからチェックしてから修正してください

2024-07-28 18:04 UTC, kei95 commented on src/components/SignupForm.jsx
> +      navigate("/signupsuccess");
`res.status`が409 or 500でもここのブロックにコードが到達するっぽいんだけど、もしそうならエラーだったとしてもアプリが`/signupsuccess`に行くんじゃないかな？チェックしてみて

2024-07-28 18:04 UTC, kei95 commented on package.json
> +    "@mui/material": "^5.16.4",
みた感じこのパッケージ使ってなさそう。使ってないなら消すこと。

2024-07-29 02:39 UTC, Replay95 commented
エラーハンドリング検証＆修正および不要コードの削除をしました
本来なら別々にコミットするべきなんでしょうが、リアルの仕事の時間が迫っていたため一括でプッシュしました
ご了承ください

2024-07-29 02:44 UTC, kei95 requested changes
このconsoleだけ消してくれたらapproveできそう。Good job👍

2024-07-29 02:44 UTC, kei95 commented on src/components/SignupForm.jsx
> +      console.log(res.status);
console.logはちゃんと消してからcommitしよう

2024-07-30 04:39 UTC, Replay95 commented
consoleを削除完了しました

2024-07-30 04:42 UTC, kei95 approved these changes

2024-07-31 01:13 UTC, merged